language: node_js
node_js:
- '8'
env:
  global:
  - GH_USER_EMAIL="travis@example.org"
  - GH_USER_NAME="cozy-bot"
  - DEPLOY_REPOSITORY="git@github.com:konnectors/probikeshop.git"
  - secure: XFcB+a9OFC9M/bNJEUz6FQ006r13SqYEcCIKDlwaHp41BkRwbuicbR2joW8c5UqR1Pw4KdQuS3lHpjmOyklW3C1hDjbiLTF2yWsXt/yItpLuTE1BxHuXHr9vwVjLAG0GbeDDXsjqr5l9jhlkHUQ7JQQoB3QvIyU/YDVMxvNs+SHkt/MOsv3YQuKRuGc9f0fK7UPRq0dYCZOKgxd46MEp3Nwv6G3rfNjYcJ46uUgt2tTgbyMKSbPDLjZZrE+htDBVNPsnQrYzfl1q3l8yl9j0kKpVUfD/u0vM2QCPj73mvZhSY5wAAendn5RKxfosEH2fhA0Ilh2Mu6PGcq7HGIQ8qFDSwzrZyJxr+lpjiH2Y8uqzAaFBVL5A0gP/LEdM9ejPwkxBp+XWSQoliQsvjYcM7LQz491N3qWfCvuCPr5I6L8fxal8XPKKYJqaZjirQfFjomCwaoOw6ENoDPnfK+ESZcg0UmQ/KVKck8ovhE7oQmupaRNfT5Vu4WISYI3/UNJ285o9uim3/pS2gIw7D0CikO77mSJzu71BmFsMymaZUOVbug3x4uBT8DhiW2R4XEBYK0ILa/vmErfU9Kw4HF5YUVmePUrTMLx/h+PCm+Zo0G9MgWkxHuGBDfdwgzx+xCsSzHuCs0/UsUwW6rxDtaD2HGtP9pkxamFiErA4GM5PJ6o=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
- yarn run check
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_2de1e6c7e903_key -iv $encrypted_2de1e6c7e903_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
